"""Add compiled_video_s3_key to jobs table

Revision ID: 5d6afe00ef53
Revises: 20182e5af0d8
Create Date: 2025-11-11 23:50:57.019430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d6afe00ef53"
down_revision: Union[str, Sequence[str], None] = "20182e5af0d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("compiled_video_s3_key", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "compiled_video_s3_key")
    # ### end Alembic commands ###
