"""add_api_key_column

Revision ID: b1ea30b60ccb
Revises: 5d6afe00ef53
Create Date: 2025-11-18 18:58:36.281281

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1ea30b60ccb"
down_revision: Union[str, Sequence[str], None] = "5d6afe00ef53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("gemini_api_key_encrypted", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gemini_api_key_encrypted")
    # ### end Alembic commands ###
