"""Initial migration with all tables

Revision ID: ce9ec48516b9
Revises:
Create Date: 2025-10-13 19:10:55.112778

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ce9ec48516b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('original_s3_key', sa.String(length=500), nullable=False),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('video_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('content_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('concepts', sa.JSON(), nullable=True),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_segments_id'), 'content_segments', ['id'], unique=False)
    op.create_index(op.f('ix_content_segments_importance_score'), 'content_segments', ['importance_score'], unique=False)
    op.create_index(op.f('ix_content_segments_job_id'), 'content_segments', ['job_id'], unique=False)
    op.create_index(op.f('ix_content_segments_segment_id'), 'content_segments', ['segment_id'], unique=True)
    op.create_index(op.f('ix_content_segments_segment_order'), 'content_segments', ['segment_order'], unique=False)
    op.create_index(op.f('ix_content_segments_start_time'), 'content_segments', ['start_time'], unique=False)
    op.create_table('layout_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('screen_region', sa.JSON(), nullable=False),
    sa.Column('camera_region', sa.JSON(), nullable=False),
    sa.Column('split_ratio', sa.Float(), nullable=False),
    sa.Column('layout_type', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sample_frame_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layout_analysis_id'), 'layout_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_layout_analysis_job_id'), 'layout_analysis', ['job_id'], unique=True)
    op.create_index(op.f('ix_layout_analysis_layout_id'), 'layout_analysis', ['layout_id'], unique=True)
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_logs_created_at'), 'processing_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_logs_id'), 'processing_logs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_logs_job_id'), 'processing_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_processing_logs_log_id'), 'processing_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_processing_logs_stage'), 'processing_logs', ['stage'], unique=False)
    op.create_table('silence_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('silence_type', sa.String(length=20), nullable=False),
    sa.Column('amplitude_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silence_regions_id'), 'silence_regions', ['id'], unique=False)
    op.create_index(op.f('ix_silence_regions_job_id'), 'silence_regions', ['job_id'], unique=False)
    op.create_index(op.f('ix_silence_regions_region_id'), 'silence_regions', ['region_id'], unique=True)
    op.create_index(op.f('ix_silence_regions_start_time'), 'silence_regions', ['start_time'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('speaker_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    op.create_index(op.f('ix_transcripts_job_id'), 'transcripts', ['job_id'], unique=False)
    op.create_index(op.f('ix_transcripts_segment_id'), 'transcripts', ['segment_id'], unique=True)
    op.create_index(op.f('ix_transcripts_start_time'), 'transcripts', ['start_time'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('content_segment_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_s3_key', sa.String(length=500), nullable=True),
    sa.Column('subtitle_s3_key', sa.String(length=500), nullable=True),
    sa.Column('clip_order', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_segment_id'], ['content_segments.segment_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_clip_id'), 'clips', ['clip_id'], unique=True)
    op.create_index(op.f('ix_clips_clip_order'), 'clips', ['clip_order'], unique=False)
    op.create_index(op.f('ix_clips_content_segment_id'), 'clips', ['content_segment_id'], unique=False)
    op.create_index(op.f('ix_clips_id'), 'clips', ['id'], unique=False)
    op.create_index(op.f('ix_clips_importance_score'), 'clips', ['importance_score'], unique=False)
    op.create_index(op.f('ix_clips_job_id'), 'clips', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clips_job_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_importance_score'), table_name='clips')
    op.drop_index(op.f('ix_clips_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_content_segment_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_clip_order'), table_name='clips')
    op.drop_index(op.f('ix_clips_clip_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_transcripts_start_time'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_segment_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_job_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_silence_regions_start_time'), table_name='silence_regions')
    op.drop_index(op.f('ix_silence_regions_region_id'), table_name='silence_regions')
    op.drop_index(op.f('ix_silence_regions_job_id'), table_name='silence_regions')
    op.drop_index(op.f('ix_silence_regions_id'), table_name='silence_regions')
    op.drop_table('silence_regions')
    op.drop_index(op.f('ix_processing_logs_stage'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_log_id'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_job_id'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_id'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_created_at'), table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index(op.f('ix_layout_analysis_layout_id'), table_name='layout_analysis')
    op.drop_index(op.f('ix_layout_analysis_job_id'), table_name='layout_analysis')
    op.drop_index(op.f('ix_layout_analysis_id'), table_name='layout_analysis')
    op.drop_table('layout_analysis')
    op.drop_index(op.f('ix_content_segments_start_time'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_segment_order'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_segment_id'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_job_id'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_importance_score'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_id'), table_name='content_segments')
    op.drop_table('content_segments')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
